# Generated by Django 5.0.6 on 2024-06-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selfchatgpt2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("answer", models.TextField()),
            ],
        ),
    ]
